import pandas as pd
import numpy as np
import xarray as xr
import matplotlib.pyplot as plt
import matplotlib.colors



def nbdc_to_ds(datapath):
    '''
    Load NDBC Standard meterological data text data file into xarray dataset.
    
    INPUTS:
    data_path: path to series text file generated by nbdc.noaa.gob
    
    RETURNS:
    xarray dataset
    
    EXAMPLE:
    import pandas as pd
    import numpy as np
    import xarray as xr
    
    from buoy_tools import nbdc_to_ds
    datapath = 'nbdc_july.txt' 
    ds = nbdc_to_ds(datapath)
    '''
    
    # First two lines contain header names and units, respectively
    nhead = 2
    headerlines = list() # Create blank list for header and units
    
    # Open file and extract relevant variable names and units
    with open(datapath) as f: 
            for i in range(nhead):
                line = f.readline()
                line = line.lstrip('#') # Remove # at beginning of first line
                line = line.rstrip('\n') # Remove \n at end of first line
                line = line.replace('   ', ' ') # Remove wonky spacing and extra commas for clean list
                line = line.replace(' ', ',')
                line = line.replace(',,', ',')
                headerlines.append(line) # Append the headerline list
                
    var_names = headerlines[0].split(',') # Create list for names and units
    var_units = headerlines[1].split(',')
    
    # Create new pandas dataframe with var_names, without the 'units' row getting in the way
    df = pd.read_csv(datapath, skiprows = nhead, names = var_names, delimiter=' ', index_col = False)
    
    # String together the seperate date columns into a single cohesive datetime column
    datestr = df['YY'].map(str)+'-'+df['MM'].map(str)+'-'+df['DD'].map(str)
    timestr = df['hh'].map(str)+':'+df['mm'].map(str)
    df['datetime'] = pd.to_datetime(datestr+' '+timestr,utc=True)
    df = df.drop(columns=['YY', 'MM', 'DD', 'hh', 'mm']) # Drop the now useless seperated date and time columns
    
    # Generate an updated list of variable names, units, and descriptions for abbreviated variable names
    var_names_new = df.columns[0:13] # Creates list of all variables except 'datetime'
    var_units_new = var_units[5:] # Creates list of units that excludes 'YY', 'MM', etc.
    for i in var_units_new: # Removes any randomly created spaces in the units list
        if(len(i)==0):
            var_units_new.remove(i)
    var_desc = ['Wind direction', 'Wind speed', 'Wind gust', 'Significant wave height', 'Dominant wave period', 'Average wave period',
               'Mean wave direction', 'Atmospheric pressure', 'Air temperature', 'Water temperature', 'Dew point', 'Visibility', 'Tidal height']
    
    #Create the dataset
    ds = xr.Dataset(coords={'time': df['datetime'].values}) # Creates dataset with only time coordinate
    for i in enumerate(var_names_new):
        step = i[0] # Indicates the iteration of the loop
        name = i[1] # Indicates the current name of the variable
        
        vardata = df[str(name)].values # Call values from the dataframe corresponding to the current variable name
        
        ds[name] = ('time', vardata) # Create new variable in xarray dataset corresponding to the variable from the pandas dataframe
        
        ds[name].attrs['units'] = var_units_new[step] # Add units and variable description in the attributes section of the variable
        ds[name].attrs['description'] = var_desc[step]
        
    return ds

def m1_2d_reshape(filepath):
    ds = xr.open_dataset(filepath)
    var_names = list(ds.data_vars)
    df = pd.DataFrame({'time':ds.time, 'z':ds.z}) #, var_names[1]:ds[var_names[1]], var_names[2]:ds[var_names[2]]})
    for i in range(len(var_names)):
        df[var_names[i]] = ds[var_names[i]]
    
    depth = np.unique(df['z'])
    time = np.unique(df['time'])
    
    ds2 = xr.Dataset(coords={'time': time, 'z': depth})
    ds2.time.attrs = ds.time.attrs
    ds2.z.attrs = ds.z.attrs
    
    for var in var_names:
        if var == 'time' or var == 'z':
            pass
        else:
            var_data = df.pivot(index='time',columns='z',values=var)
            ds2[var] = (['time','z'],var_data.values)
            ds2[var].attrs = ds[var].attrs
    
    ds2.attrs = ds.attrs
    return ds2

def m1_1d_reshape(filepath):
    ds = xr.open_dataset(filepath)
    var_names = list(ds.data_vars)
    df = pd.DataFrame({'time':ds.time})
    for i in range(len(var_names)):
        df[var_names[i]] = ds[var_names[i]]
        
    time = np.unique(df['time'])
    
    ds2 = xr.Dataset(coords={'time': df['time'].values})
    ds2.time.attrs = ds.time.attrs
    for var in var_names:
        var_data = df[var]
        ds2[var] = (['time'],var_data)
        ds2[var].attrs = ds[var].attrs
    
    ds2.attrs = ds.attrs
    
    return ds2